apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: socle-cluster
  labels:
    app: socle-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    authorization: 
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: tls
#    resources:
#      requests:
#        memory: 1g
#        cpu: "1"
#      limits:
#        memory: 1g
#        cpu: "1"
#    jvmOptions:
#      -Xms: 1024m
#      -Xmx: 1024m
    config:
      inter.broker.protocol.version: "3.0"
      log.message.format.version: "3.0"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 3
      min.insync.replicas: 1
      default.replication.factor: 3
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: true
        # - id: 1
        #   type: persistent-claim
        #   size: 10Gi
        #   deleteClaim: true
  zookeeper:
    replicas: 1
#    resources:
#      requests:
#        memory: 1g
#        cpu: "1"
#      limits:
#        memory: 1g
#        cpu: "1"
#    jvmOptions:
#      -Xms: 1024m
#      -Xmx: 1024m
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}