apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-scalability-producer
  name: test-scalability-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scalability-producer
  template:
    metadata:
      labels:
        app: test-scalability-producer
    spec:
      containers:
        - name: test-scalability-producer
          image: cupidcb/springboot-kafka:latest
        - lisetener:
#          env:
#            - name: BOOTSTRAP_SERVERS
#              value: socle-cluster-kafka-bootstrap:9092
#            - name: TOPIC
#              value: test-scalability-topic
#            - name: DELAY_MS
#              value: "1000"
#            - name: LOG_LEVEL
#              value: "INFO"
#            - name: MESSAGE_COUNT
#              value: "1000000"
#            - name: PRODUCER_ACKS
#              value: "all"
#            - name: ADDITIONAL_CONFIG
#              value: |
#                retries=100