apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: socle-user
  labels:
    strimzi.io/cluster: socle-cluster 
spec:
  authentication:
    type: tls 
  authorization:
    type: simple
    acls: 
      - resource:
          type: topic
          name: socle-kafka-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: socle-kafka-topic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: socle-group
          patternType: literal
        operation: Read