apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{CLUSTER_NAME}}
  labels:
    app: {{CLUSTER_NAME}}
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    authorization: 
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: tls
#    resources:
#      requests:
#        memory: 2Gi
#        cpu: 500m
#      limits:
#        memory: 10Gi
#        cpu: 500m
#    jvmOptions:
#      -Xms: 1024m
#      -Xmx: 1024m
#      gcLoggingEnabled: false
    config:
      inter.broker.protocol.version: "3.0"
      log.message.format.version: "3.0"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
