#apiVersion: kafka.strimzi.io/v1beta2
#kind: KafkaTopic
#metadata:
#  name: connect-cluster-configs
#  labels:
#    strimzi.io/cluster: socle-cluster
#spec:
#  partitions: 3
#  replicas: 1
#  config:
#    retention.ms: 604800000 # 7 days
#    segment.bytes: 1073741824 # 1 Go
#---
#apiVersion: kafka.strimzi.io/v1beta2
#kind: KafkaTopic
#metadata:
#  name: connect-cluster-status
#  labels:
#    strimzi.io/cluster: socle-cluster
#spec:
#  partitions: 3
#  replicas: 1
#  config:
#    retention.ms: 604800000 # 7 days
#    segment.bytes: 1073741824 # 1 Go
#---
#apiVersion: kafka.strimzi.io/v1beta2
#kind: KafkaTopic
#metadata:
#  name: connect-cluster-offsets
#  labels:
#    strimzi.io/cluster: socle-cluster
#spec:
#  partitions: 3
#  replicas: 1
#  config:
#    retention.ms: 604800000 # 7 days
#    segment.bytes: 1073741824 # 1 Go
#---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: socle-kafka-connect-user
  labels:
    strimzi.io/cluster: socle-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: group
        name: connect-cluster
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Create
    # Additional topics and groups used by connectors
    # Change to match the topics used by your connectors
    - resource:
        type: group
        name: connect-cluster
      operation: Read
    - resource:
        type: topic
        name: socle-kafka-topic
      operation: Read
    - resource:
        type: topic
        name: socle-kafka-topic
      operation: Describe
    - resource:
        type: topic
        name: socle-kafka-topic
      operation: Write
    - resource:
        type: topic
        name: socle-kafka-topic
      operation: Create
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: socle-kafka-connect
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.0.0
  replicas: 1
  bootstrapServers: socle-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: socle-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
